### ISSUE TITLE
Need new rest endpoint for BAGIS-P settings

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/django-ebagis#80]
@jduh has requested that we provide the capability to load some default PC client settings in BAGIS-P. Can we get another endpoint similar to /api/rest/desktop/settings/? It should work the same as the aforementioned endpoint but have a unique file name in C:\ebagis\. The file name for the aforementioned endpoint is settings.yaml. 

I'm attaching a sample json file for the endpoint. This is just a prototype but if we can get this to work, it is easy to add new fields. Thank you!

[bagisp_datasources.txt](https://github.com/PSU-CSAR/django-ebagis/files/1459514/bagisp_datasources.txt)

**Comment by jkeifer** [comment]
This request should be fairly easy to accommodate. Is there a specific reason the new endpoint settings need to be from a different yaml file, or could I add a new section to the existing file?

**Comment by lbross** [comment]
This is for a different desktop module and the data structure is different but I suppose it could go into the existing yaml file. Are you still planning on supporting a new second endpoint? If not, let me work on some options for formatting/parsing the output of a combined file without breaking the module that is using the existing endpoint.

**Comment by jkeifer** [comment]
This is done and in production. I simply restructured the existing yaml file like so:
```
bagis:
  terrain: BAGIS_Reference_Maps.lyr
  dem10: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_GISLayers/DEM_westus_bc_30m/ImageServer
  dem30: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_GISLayers/DEM_westus_bc_30m/ImageServer
  preferredDem: dem30
  demElevUnit: Meters
  gaugeStation: http://bagis.geog.pdx.edu/arcgis/rest/services/AWDB_ACTIVE/stations_USGS_ACTIVE/FeatureServer/0
  gaugeStationName: name
  gaugeStationArea: basinarea
  gaugeStationUnits: Square Mile
  snotel: http://bagis.geog.pdx.edu/arcgis/rest/services/AWDB_ACTIVE/stations_SNTL_ACTIVE/FeatureServer/0
  snotelElev: elevation
  snotelName: name
  snowCourse: http://bagis.geog.pdx.edu/arcgis/rest/services/AWDB_ACTIVE/stations_SNOW_ACTIVE/FeatureServer/0
  snowCourseElev: elevation
  snowCourseName: name
  prism: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_PRISM_1981_2010

bagis-p:
  datasources:
    - id: 1
      name: Test_1
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/PRISM_1981_2010_tmax_august/ImageServer
    - id: 2
      name: Test_2
      source: http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/PRISM_1981_2010_tmin_august/ImageServer

bagis-h: []
```

To get the settings for each of these modules, use the following endpoints:
  - bagis: /api/rest/desktop/settings/ or /api/rest/desktop/settings/bagis/
  - bagis-p: /api/rest/desktop/settings/bagis-p/
  - bagis-h: /api/rest/desktop/settings/bagis-h/

If new modules are ever added and require settings, or additional endpoints are needed, I made it super simple to add new endpoints. Just add the key to the yaml file and add the key to the URL config for this endpoint in the rest-urls.py file:

In the yaml:
```
...
bagis_h: []

new-endpoint-key:
  some_setting: value
```

And then in the url config:
```
url(r"^desktop/settings/(?P<module>bagis|bagis-p|bagis-h|new-endpoint-key)/$",
        views.get_settings),
```

The response from the bagis-p endpoint is almost what you proposed. Here is what it looks like:
```
{
    "datasources": [
        {
            "source": "http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/PRISM_1981_2010_tmax_august/ImageServer",
            "id": 1,
            "name": "Test_1"
        },
        {
            "source": "http://bagis.geog.pdx.edu/arcgis/services/BAGIS_Databin/PRISM_1981_2010_tmin_august/ImageServer",
            "id": 2,
            "name": "Test_2"
        }
    ]
}
```

Notice that the data sources list is under the datasources key. I did that so any new settings could be added without making any changes to the data sources settings.
